default_install_hook_types: [ pre-commit, commit-msg ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        args: ["--allow-multiple-documents"]
      - id: detect-aws-credentials
        stages: [pre-commit]
        args: ["--allow-missing-credentials"]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.4
    hooks:
      - id: golangci-lint
        stages: [pre-commit]
        args: ["--timeout=10m"]
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports
        stages: [pre-commit]
