version: "3.0"
services:
  db:
    image: timescale/timescaledb:2.13.0-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: trading-chart-service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  push_gateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
