name: Initialize project
on:
  push:
    branches:
      - main
jobs:
  init:
    if: ${{ github.repository != 'honestbank/template-repository-go' }}
    runs-on: ubuntu-latest
    name: init project
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Zsh
        run: sudo apt-get install zsh
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.ENGINEERING_GPG_PRIVATE_KEY }}
          git-user-signingkey: true
          git-config-global: true
          git-commit-gpgsign: true
      - name: Configure ssh-key for private modules
        env:
          SSH_KEY: ${{ secrets.ENGINEERING_SSH_KEY }}
        run: mkdir -p ~/.ssh; echo "$SSH_KEY" > ~/.ssh/id_rsa; chmod 600 ~/.ssh/id_rsa; git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Set env
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: run init script
        run: |
          bash .github/init.sh REPO=$REPO_NAME
          zsh ./catalog-info.generator.sh
          rm -Rf .github/init.sh
      - name: push changes
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ENGINEERING_GITHUB_PERSONAL_ACCESS_TOKEN }}
          commit-message: "chore(project): initializing project"
          committer: "Honestbank Bot <engineering+githubaction@honestbank.com>"
          author: "Honestbank Bot <engineering+githubaction@honestbank.com>"
          branch: automated/init
          title: "chore(project): initializing project"
