# DO NOT CHANGE. This file is being managed from a central repository
# To know more simply visit https://github.com/honestbank/.github/blob/main/docs/about.md

name: repository-pre-commit-checks

on:
  pull_request:
    branches: [main, master]

jobs:
  load-secrets:
    uses: "./.github/workflows/secrets-loader.yaml"
    secrets: inherit
  repository-pre-commit-checks:
    name: repository-pre-commit-checks
    needs:
      - load-secrets
    uses: honestbank/workflows/.github/workflows/shared-pre-commit-checks-go.yaml@main
    secrets: inherit
    with:
      encrypted_secrets : ${{ needs.load-secrets.outputs.encrypted_secrets }}
