# DO NOT CHANGE. This file is being managed from a central repository
# To know more simply visit https://github.com/honestbank/.github/blob/main/docs/about.md

# yamllint disable rule:line-length
# Use template from https://github.com/honestbank/workflows/tree/main/examples/repository-workflows
---
name: "repository-semantic-pr"
permissions:
  contents: write
  pull-requests: write

on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  repository-semantic-pr:
    name: repository-semantic-pr
    uses: honestbank/workflows/.github/workflows/shared-semantic-pr.yaml@main
    secrets: inherit
